// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const datasourceUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];

if (!datasourceUrl) {
  throw new Error("Prisma datasource URL is not set. Define DIRECT_URL or DATABASE_URL.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --experimental-strip-types prisma/seed.ts",
  },
  datasource: {
    url: datasourceUrl,
  },
});
